name: CI Checks

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest # <2>
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run Test
        run: make test # <1>
      - name: Coverage Check
        run: make coverage # <2>
      - name: Generate Report
        run: make report # <3>
      - name: Copy Files
        run: |
          mkdir  reports
          cp cover.html reports/.

      - name: Archive # <4>
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
      - name: Check out code into the Go module directory #
        uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Copy Files #
        run: |
          mkdir  artifacts
          cp api artifacts/.

      - name: Archive #
        uses: actions/upload-artifact@v4
        with:
          name: api #
          path: artifacts